import type { Asset, SocialDraft } from '@/lib/domain/types'
import { appendSeedAssets } from '@/lib/seeds/assets'
import { classifyAspectRatio } from './aspect'
import { composeTextInImageThumbnail } from './thumbnail-compose'
import {
  assignGeneratedThumbnailsToDrafts,
  autoGeneratedThumbsFrom,
  landscapeThumbnailAssets,
  planThumbnailFile,
  portraitCoverAssets,
  type GeneratedThumbAsset,
} from './thumbnail-assign'
import { resolveThumbnailHook } from './thumbnail-hook'
import {
  buildThumbnailOverlaySpec,
  candidateAnchors,
  chooseTextAnchor,
  cropIsLetterboxed,
  pickFillForRegion,
  regionLumaVariance,
  regionMeanLuma,
  scoreThumbnailCandidate,
  SHORT_COVER_HEIGHT,
  SHORT_COVER_WIDTH,
  YOUTUBE_THUMB_HEIGHT,
  YOUTUBE_THUMB_WIDTH,
} from './thumbnail-layout'
import { captureCandidateStills } from './thumbnail-stills'

export { assignGeneratedThumbnailsToDrafts, autoGeneratedThumbsFrom }

const MIN_AUTO_THUMBS = 2

export interface ThumbnailGenerationResult {
  ok: boolean
  assets: Asset[]
  drafts: SocialDraft[]
  hook: string
  message: string
}

function pickLandscapeVideo(assets: Asset[]): Asset | undefined {
  const videos = assets.filter((asset) => asset.type === 'video' && Boolean(asset.url))
  return videos.find((asset) => asset.aspectRatio === '16:9')
    ?? videos.find((asset) => asset.aspectRatio !== '9:16')
}

function pickPortraitVideo(assets: Asset[]): Asset | undefined {
  return assets.find((asset) => asset.type === 'video' && Boolean(asset.url) && asset.aspectRatio === '9:16')
}

async function fileFromAsset(asset: Asset): Promise<File> {
  const response = await fetch(asset.url)
  if (!response.ok) throw new Error('素材ファイルを取得できませんでした。')
  const blob = await response.blob()
  return new File([blob], asset.name, { type: blob.type || 'video/mp4' })
}

async function samplePixels(blob: Blob, width: number, height: number): Promise<Uint8ClampedArray | null> {
  if (typeof createImageBitmap !== 'function' || typeof document === 'undefined') return null
  const bitmap = await createImageBitmap(blob)
  try {
    const canvas = document.createElement('canvas')
    canvas.width = width
    canvas.height = height
    const context = canvas.getContext('2d')
    if (!context) return null
    context.drawImage(bitmap, 0, 0, width, height)
    return context.getImageData(0, 0, width, height).data
  } finally {
    bitmap.close()
  }
}

async function composeOne(params: {
  still: { blob: Blob; width: number; height: number; timeRatio: number }
  orientation: '16:9' | '9:16'
  hook: string
  index: number
  preferredAnchor?: ReturnType<typeof candidateAnchors>[number]
}): Promise<{ file: File; score: number; plan: ReturnType<typeof planThumbnailFile> } | null> {
  const targetW = params.orientation === '16:9' ? YOUTUBE_THUMB_WIDTH : SHORT_COVER_WIDTH
  const targetH = params.orientation === '16:9' ? YOUTUBE_THUMB_HEIGHT : SHORT_COVER_HEIGHT
  const spec = buildThumbnailOverlaySpec({
    orientation: params.orientation,
    hook: params.hook,
    sourceWidth: params.still.width,
    sourceHeight: params.still.height,
    anchor: params.preferredAnchor,
  })

  if (cropIsLetterboxed(spec.crop, params.still.width, params.still.height)) {
    return null
  }

  const sampled = await samplePixels(params.still.blob, Math.min(params.still.width, 320), Math.min(params.still.height, 180))
  if (sampled) {
    const sampleW = Math.min(params.still.width, 320)
    const sampleH = Math.min(params.still.height, 180)
    const anchor = params.preferredAnchor ?? chooseTextAnchor(sampled, sampleW, sampleH, params.orientation)
    spec.anchor = anchor
    if (anchor === 'left') {
      spec.x = spec.width * 0.28
      spec.y = spec.height * 0.5
    } else if (anchor === 'right') {
      spec.x = spec.width * 0.72
      spec.y = spec.height * 0.5
    } else if (anchor === 'top') {
      spec.x = spec.width * 0.5
      spec.y = spec.height * 0.22
    } else {
      spec.x = spec.width * 0.5
      spec.y = spec.height * 0.82
    }
    const textRegion = anchor === 'left'
      ? { x: 0, y: 0, width: sampleW * 0.42, height: sampleH }
      : anchor === 'right'
        ? { x: sampleW * 0.58, y: 0, width: sampleW * 0.42, height: sampleH }
        : anchor === 'top'
          ? { x: 0, y: 0, width: sampleW, height: sampleH * 0.38 }
          : { x: 0, y: sampleH * 0.62, width: sampleW, height: sampleH * 0.38 }
    spec.fill = pickFillForRegion(regionMeanLuma(sampled, sampleW, textRegion))
  }

  try {
    const jpeg = await composeTextInImageThumbnail(params.still.blob, spec)
    const plan = planThumbnailFile({ orientation: params.orientation, index: params.index, hook: params.hook })
    const file = new File([jpeg], plan.fileName, { type: 'image/jpeg' })
    const score = scoreThumbnailCandidate({
      timeRatio: params.still.timeRatio,
      textRegionVariance: sampled ? regionLumaVariance(sampled, Math.min(params.still.width, 320), { x: 0, y: 0, width: 80, height: 80 }) : 0,
      subjectRegionVariance: sampled ? regionLumaVariance(sampled, Math.min(params.still.width, 320), { x: 80, y: 0, width: 80, height: 80 }) : 1,
    })
    if (file.size < 4096) return null
    if (classifyAspectRatio(targetW, targetH) !== params.orientation) return null
    return { file, score, plan }
  } catch {
    return null
  }
}

async function generateForVideo(params: {
  workspaceId: string
  seedId: string
  video: Asset
  orientation: '16:9' | '9:16'
  hook: string
}): Promise<Array<Asset & { score: number }>> {
  const file = await fileFromAsset(params.video)
  const stills = await captureCandidateStills(file, 3)
  if (stills.length === 0) return []

  const anchors = candidateAnchors(params.orientation)
  const built: { file: File; score: number; plan: ReturnType<typeof planThumbnailFile> }[] = []

  for (let index = 0; index < stills.length; index += 1) {
    const composed = await composeOne({
      still: stills[index],
      orientation: params.orientation,
      hook: params.hook,
      index: index + 1,
      preferredAnchor: anchors[index],
    })
    if (composed) built.push(composed)
  }

  if (built.length === 0) return []

  const saved: Array<Asset & { score: number }> = []
  for (const item of built) {
    const [asset] = await appendSeedAssets({
      workspaceId: params.workspaceId,
      seedId: params.seedId,
      files: [item.file],
      mediaRole: item.plan.mediaRole,
      sourceAssetId: params.video.id,
      publishingChannels: item.plan.publishingChannels,
      aspectRatio: item.plan.aspectRatio,
    })
    if (asset) saved.push({ ...asset, score: item.score })
  }
  return saved
}

export async function generatePerformanceThumbnailsForSeed(params: {
  workspaceId: string
  seedId: string
  seedTitle: string
  assets: Asset[]
  drafts: SocialDraft[]
}): Promise<ThumbnailGenerationResult> {
  const youtubeDraft = params.drafts.find((draft) => draft.channel === 'youtube')
  const proposed = typeof youtubeDraft?.metadata?.thumbnailHook === 'string'
    ? youtubeDraft.metadata.thumbnailHook
    : undefined
  const resolved = resolveThumbnailHook({
    proposed,
    title: youtubeDraft?.title,
    seedTitle: params.seedTitle,
  })

  if (!resolved.hook) {
    return {
      ok: false,
      assets: [],
      drafts: params.drafts,
      hook: '',
      message: 'フック文言を3〜8文字にできなかったため、文字入りサムネイルは作っていません。PNG/JPGをアップロードしてください。',
    }
  }

  const draftsWithAssumption = resolved.assumption
    ? params.drafts.map((draft) => {
        if (draft.channel !== 'youtube') return draft
        if (draft.assumptions.includes(resolved.assumption as string)) return draft
        return { ...draft, assumptions: [...draft.assumptions, resolved.assumption as string] }
      })
    : params.drafts

  const landscapeVideo = pickLandscapeVideo(params.assets)
  const portraitVideo = pickPortraitVideo(params.assets)
  if (!landscapeVideo && !portraitVideo) {
    return {
      ok: false,
      assets: [],
      drafts: draftsWithAssumption,
      hook: resolved.hook,
      message: '動画がないため、文字入りサムネイルは作っていません。素材管理に動画を追加するか、PNG/JPGをアップロードしてください。',
    }
  }

  const existing = autoGeneratedThumbsFrom(params.assets)
  const hasLandscape = landscapeThumbnailAssets(existing).length >= MIN_AUTO_THUMBS
  const hasPortrait = !portraitVideo || portraitCoverAssets(existing).length >= MIN_AUTO_THUMBS

  const created: Array<Asset & { score: number }> = []
  const failures: string[] = []

  if (landscapeVideo && !hasLandscape) {
    try {
      const thumbs = await generateForVideo({
        workspaceId: params.workspaceId,
        seedId: params.seedId,
        video: landscapeVideo,
        orientation: '16:9',
        hook: resolved.hook,
      })
      if (thumbs.length === 0) {
        failures.push('16:9の静止画を切り出せませんでした。')
      } else {
        created.push(...thumbs)
      }
    } catch (cause) {
      failures.push(cause instanceof Error ? cause.message : '16:9サムネイルの作成に失敗しました。')
    }
  }

  if (portraitVideo && !hasPortrait) {
    try {
      const covers = await generateForVideo({
        workspaceId: params.workspaceId,
        seedId: params.seedId,
        video: portraitVideo,
        orientation: '9:16',
        hook: resolved.hook,
      })
      if (covers.length === 0) {
        failures.push('9:16のカバー静止画を切り出せませんでした。横動画をレターボックスしません。')
      } else {
        created.push(...covers)
      }
    } catch (cause) {
      failures.push(cause instanceof Error ? cause.message : '9:16カバーの作成に失敗しました。')
    }
  }

  const combined: GeneratedThumbAsset[] = [
    ...existing.map((asset) => ({
      id: asset.id,
      name: asset.name,
      mediaRole: asset.mediaRole,
      aspectRatio: asset.aspectRatio,
      sourceAssetId: asset.sourceAssetId,
      score: 1,
    })),
    ...created.map((asset) => ({
      id: asset.id,
      name: asset.name,
      mediaRole: asset.mediaRole,
      aspectRatio: asset.aspectRatio,
      sourceAssetId: asset.sourceAssetId,
      score: asset.score,
    })),
  ]

  if (landscapeThumbnailAssets(combined).length === 0 && portraitCoverAssets(combined).length === 0) {
    return {
      ok: false,
      assets: created,
      drafts: draftsWithAssumption,
      hook: resolved.hook,
      message: failures[0]
        ?? '動画から静止画を切り出せなかったため、自動サムネイルは作っていません。PNG/JPGをアップロードしてください。',
    }
  }

  const assigned = assignGeneratedThumbnailsToDrafts(draftsWithAssumption, combined)
  const createdCount = created.length
  const reused = createdCount === 0
  const hasDrafts = params.drafts.some((draft) => draft.channel === 'youtube' || draft.channel === 'instagram')
  const createdMessage = hasDrafts
    ? `文字入りサムネイルを${createdCount}枚作成し、YouTube案に一番強い候補を選びました。下書きで切り替えできます。`
    : `文字入りサムネイルを${createdCount}枚作成しました。下書きスタジオで候補を選べます。`
  const reusedMessage = hasDrafts
    ? `既存の文字入りサムネイル（${combined.length}枚）をYouTube案に割り当てました。下書きで切り替えできます。`
    : `文字入りサムネイルはすでに${combined.length}枚あります。`
  return {
    ok: true,
    assets: created,
    drafts: assigned,
    hook: resolved.hook,
    message: reused ? reusedMessage : createdMessage,
  }
}
