import { describe, expect, it } from 'vitest'
import type { SocialDraft } from '@/lib/domain/types'
import {
  assignGeneratedThumbnailsToDrafts,
  autoGeneratedThumbsFrom,
  isAutoGeneratedThumbName,
  pickDefaultReelCover,
  pickDefaultYoutubeThumbnail,
  planThumbnailFile,
  type GeneratedThumbAsset,
} from './thumbnail-assign'

const THUMB_A = '11111111-1111-4111-8111-111111111111'
const THUMB_B = '22222222-2222-4222-8222-222222222222'
const COVER_A = '33333333-3333-4333-8333-333333333333'
const COVER_B = '44444444-4444-4444-8444-444444444444'

function thumb(over: Partial<GeneratedThumbAsset> & { id: string }): GeneratedThumbAsset {
  return {
    name: `文字サムネ-1-無料公開.jpg`,
    mediaRole: 'thumbnail',
    aspectRatio: '16:9',
    score: 1,
    ...over,
  }
}

function draft(channel: SocialDraft['channel'], over: Partial<SocialDraft> = {}): SocialDraft {
  return {
    id: `d-${channel}`,
    workspaceId: 'w',
    seedId: 's',
    channel,
    draftText: 'body',
    hashtags: [],
    assumptions: [],
    metadata: {},
    source: 'template',
    tone: 'calm',
    length: 'short',
    status: 'draft',
    createdBy: 'u',
    createdAt: '2026-08-28T00:00:00Z',
    updatedAt: '2026-08-28T00:00:00Z',
    ...over,
  }
}

describe('planThumbnailFile', () => {
  it('names a real 16:9 file with media_role thumbnail, not a text idea', () => {
    expect(planThumbnailFile({ orientation: '16:9', index: 1, hook: '無料公開' })).toEqual({
      fileName: '文字サムネ-1-無料公開.jpg',
      mediaRole: 'thumbnail',
      aspectRatio: '16:9',
      publishingChannels: ['youtube'],
    })
    expect(isAutoGeneratedThumbName('文字サムネ-1-無料公開.jpg')).toBe(true)
  })

  it('names a 9:16 cover still for Shorts/Reels/TikTok', () => {
    const plan = planThumbnailFile({ orientation: '9:16', index: 2, hook: '今すぐ' })
    expect(plan.mediaRole).toBe('cover')
    expect(plan.aspectRatio).toBe('9:16')
    expect(plan.publishingChannels).toContain('instagram')
  })
})

describe('pickDefaultYoutubeThumbnail', () => {
  const landscape = [
    thumb({ id: THUMB_A, score: 1.1 }),
    thumb({ id: THUMB_B, score: 2.4, name: '文字サムネ-2-無料公開.jpg' }),
  ]
  const portraits = [
    thumb({ id: COVER_A, mediaRole: 'cover', aspectRatio: '9:16', score: 3, name: '文字カバー-1-今すぐ.jpg' }),
    thumb({ id: COVER_B, mediaRole: 'cover', aspectRatio: '9:16', score: 1, name: '文字カバー-2-今すぐ.jpg' }),
  ]

  it('defaults the YouTube long-form draft to the strongest 16:9 thumbnail asset', () => {
    expect(pickDefaultYoutubeThumbnail([...landscape, ...portraits], false)?.id).toBe(THUMB_B)
  })

  it('uses a 9:16 cover still for Shorts instead of a 16:9 letterbox', () => {
    const picked = pickDefaultYoutubeThumbnail([...landscape, ...portraits], true)
    expect(picked?.id).toBe(COVER_A)
    expect(picked?.aspectRatio).toBe('9:16')
    expect(picked?.id).not.toBe(THUMB_B)
  })
})

describe('assignGeneratedThumbnailsToDrafts', () => {
  const generated = [
    thumb({ id: THUMB_B, score: 5 }),
    thumb({ id: COVER_A, mediaRole: 'cover', aspectRatio: '9:16', score: 4, name: '文字カバー-1-今すぐ.jpg' }),
  ]

  it('writes thumbnailAssetId onto the YouTube draft', () => {
    const [youtube] = assignGeneratedThumbnailsToDrafts([draft('youtube')], generated)
    expect(youtube.metadata.thumbnailAssetId).toBe(THUMB_B)
  })

  it('does not attach a 16:9 thumbnail to a Shorts draft; records the 9:16 cover instead', () => {
    const [youtube] = assignGeneratedThumbnailsToDrafts(
      [draft('youtube', { metadata: { isShort: true } })],
      generated,
    )
    expect(youtube.metadata.thumbnailAssetId).toBeUndefined()
    expect(youtube.metadata.coverAssetId).toBe(COVER_A)
  })

  it('assigns the 9:16 cover to Instagram Reels and leaves TikTok without a fake cover image', () => {
    const [instagram, tiktok] = assignGeneratedThumbnailsToDrafts(
      [draft('instagram'), draft('tiktok')],
      generated,
    )
    expect(instagram.metadata.coverAssetId).toBe(COVER_A)
    expect(tiktok.metadata.coverAssetId).toBeUndefined()
    expect(pickDefaultReelCover(generated)?.aspectRatio).toBe('9:16')
  })
})

describe('autoGeneratedThumbsFrom', () => {
  it('only counts real auto files, not user source images', () => {
    const assets = [
      { id: THUMB_A, workspaceId: 'w', name: '文字サムネ-1-無料公開.jpg', url: 'https://x/a.jpg', type: 'image' as const, size: 10, uploadedBy: 'u', createdAt: '', mediaRole: 'thumbnail' as const },
      { id: COVER_B, workspaceId: 'w', name: 'photo.jpg', url: 'https://x/b.jpg', type: 'image' as const, size: 10, uploadedBy: 'u', createdAt: '', mediaRole: 'source' as const },
    ]
    expect(autoGeneratedThumbsFrom(assets).map((asset) => asset.id)).toEqual([THUMB_A])
  })
})
