import type { Asset, AssetAspectRatio, AssetMediaRole, PublishingChannel, SocialDraft } from '@/lib/domain/types'
import { mergeDraftPublishOptions } from '@/lib/publish/draft-publish-options'

export const AUTO_THUMB_PREFIX = '文字サムネ-'
export const AUTO_COVER_PREFIX = '文字カバー-'

export interface GeneratedThumbAsset {
  id: string
  name: string
  mediaRole?: AssetMediaRole
  aspectRatio?: AssetAspectRatio
  sourceAssetId?: string
  score?: number
}

export function isAutoGeneratedThumbName(name: string): boolean {
  return name.startsWith(AUTO_THUMB_PREFIX) || name.startsWith(AUTO_COVER_PREFIX)
}

export function autoGeneratedThumbsFrom(assets: Asset[], sourceAssetId?: string): Asset[] {
  return assets.filter((asset) => {
    if (asset.type !== 'image') return false
    if (!isAutoGeneratedThumbName(asset.name)) return false
    if (sourceAssetId && asset.sourceAssetId && asset.sourceAssetId !== sourceAssetId) return false
    return asset.mediaRole === 'thumbnail' || asset.mediaRole === 'cover'
  })
}

export function landscapeThumbnailAssets(assets: GeneratedThumbAsset[]): GeneratedThumbAsset[] {
  return assets.filter((asset) => asset.mediaRole === 'thumbnail' && asset.aspectRatio === '16:9')
}

export function portraitCoverAssets(assets: GeneratedThumbAsset[]): GeneratedThumbAsset[] {
  return assets.filter((asset) => (
    (asset.mediaRole === 'cover' || asset.mediaRole === 'thumbnail')
    && asset.aspectRatio === '9:16'
  ))
}

function strongest(assets: GeneratedThumbAsset[]): GeneratedThumbAsset | undefined {
  if (assets.length === 0) return undefined
  return [...assets].sort((left, right) => (right.score ?? 0) - (left.score ?? 0))[0]
}

export function pickDefaultYoutubeThumbnail(assets: GeneratedThumbAsset[], isShort: boolean): GeneratedThumbAsset | undefined {
  if (isShort) {
    // Shorts cannot use YouTube custom thumbnails. A 9:16 cover still is the
    // honest default visual — never a 16:9 letterbox.
    return strongest(portraitCoverAssets(assets))
  }
  return strongest(landscapeThumbnailAssets(assets))
}

export function pickDefaultReelCover(assets: GeneratedThumbAsset[]): GeneratedThumbAsset | undefined {
  return strongest(portraitCoverAssets(assets))
}

export interface ThumbnailFilePlan {
  fileName: string
  mediaRole: AssetMediaRole
  aspectRatio: AssetAspectRatio
  publishingChannels: PublishingChannel[]
}

export function planThumbnailFile(params: {
  orientation: '16:9' | '9:16'
  index: number
  hook: string
}): ThumbnailFilePlan {
  if (params.orientation === '9:16') {
    return {
      fileName: `${AUTO_COVER_PREFIX}${params.index}-${params.hook}.jpg`,
      mediaRole: 'cover',
      aspectRatio: '9:16',
      publishingChannels: ['instagram', 'youtube'],
    }
  }
  return {
    fileName: `${AUTO_THUMB_PREFIX}${params.index}-${params.hook}.jpg`,
    mediaRole: 'thumbnail',
    aspectRatio: '16:9',
    publishingChannels: ['youtube'],
  }
}

/**
 * Default-select the strongest generated still on channel drafts.
 * Shorts / Reels get a 9:16 cover still. YouTube long-form gets a 16:9
 * thumbnail. TikTok does not get a cover image (API cannot attach one).
 */
export function assignGeneratedThumbnailsToDrafts(
  drafts: SocialDraft[],
  generated: GeneratedThumbAsset[],
): SocialDraft[] {
  return drafts.map((draft) => {
    const isShort = draft.metadata?.isShort === true
    if (draft.channel === 'youtube') {
      const picked = pickDefaultYoutubeThumbnail(generated, isShort)
      if (!picked) return draft
      if (isShort) {
        // Do not set thumbnailAssetId — YouTube Shorts reject custom thumbs.
        // The 9:16 still is recorded as coverAssetId for studio preview / Reels reuse.
        return {
          ...draft,
          metadata: mergeDraftPublishOptions(draft.metadata, { coverAssetId: picked.id, thumbnailAssetId: undefined }),
        }
      }
      return {
        ...draft,
        metadata: mergeDraftPublishOptions(draft.metadata, { thumbnailAssetId: picked.id }),
      }
    }

    if (draft.channel === 'instagram') {
      const picked = pickDefaultReelCover(generated)
      if (!picked) return draft
      return {
        ...draft,
        metadata: mergeDraftPublishOptions(draft.metadata, { coverAssetId: picked.id }),
      }
    }

    return draft
  })
}
