-- Messaging concierge PR-B: AI reply generation shares ONE cost ledger and
-- monthly budget cap with draft generation. A DM reply has no Seed and no
-- publishing channel, so ai_generations is relaxed to also allow a reply row
-- keyed by inbox_item_id, discriminated by `purpose`. Also wires up the
-- pre-existing (but never-written) ai_reply_suggestions table with the columns
-- the reply-generate route needs.

BEGIN;

-- ── ai_generations: allow reply rows (no seed, no channel) ──────────────────
ALTER TABLE public.ai_generations ALTER COLUMN seed_id DROP NOT NULL;

ALTER TABLE public.ai_generations
  ADD COLUMN inbox_item_id UUID REFERENCES public.inbox_items(id) ON DELETE CASCADE,
  ADD COLUMN purpose TEXT NOT NULL DEFAULT 'draft';

-- Existing rows are all drafts with seed_id set, so both checks hold for them.
ALTER TABLE public.ai_generations
  ADD CONSTRAINT ai_generations_purpose_check CHECK (purpose IN ('draft', 'reply')),
  ADD CONSTRAINT ai_generations_target_check CHECK (
    (purpose = 'draft' AND seed_id IS NOT NULL)
    OR (purpose = 'reply' AND inbox_item_id IS NOT NULL)
  );

CREATE INDEX ai_generations_inbox_item_id_idx ON public.ai_generations(inbox_item_id);

COMMENT ON COLUMN public.ai_generations.purpose IS
  'draft = channel draft from a Seed (seed_id set); reply = DM reply suggestion (inbox_item_id set). One shared cost ledger + monthly budget cap covers both. channels stays NOT NULL DEFAULT {} — reply rows use the empty default.';

-- The existing "Contributors can record AI generations" INSERT policy
-- (owner/admin/editor/contributor) already permits the reply route's callers;
-- the route gates more tightly on reply_inbox, so no policy change is needed.

-- ── ai_reply_suggestions: add the columns the reply route writes ────────────
-- The table has existed since the initial schema but nothing ever wrote it, so
-- it is empty and workspace_id can go straight to NOT NULL.
ALTER TABLE public.ai_reply_suggestions
  ADD COLUMN workspace_id UUID REFERENCES public.workspaces(id) ON DELETE CASCADE,
  ADD COLUMN source TEXT NOT NULL DEFAULT 'ai',
  ADD COLUMN assumptions TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN ai_generation_id UUID REFERENCES public.ai_generations(id) ON DELETE SET NULL;

ALTER TABLE public.ai_reply_suggestions
  ALTER COLUMN workspace_id SET NOT NULL,
  ADD CONSTRAINT ai_reply_suggestions_source_check CHECK (source IN ('template', 'ai'));

CREATE INDEX ai_reply_suggestions_workspace_id_idx ON public.ai_reply_suggestions(workspace_id);

COMMENT ON COLUMN public.ai_reply_suggestions.source IS
  'ai = generated by Anthropic; template = deterministic fallback shown honestly when Anthropic is unconfigured.';

-- INSERT stays service-role-only (no policy) — the reply-generate route writes
-- suggestions with the service client, exactly like inbox_items ingestion. The
-- existing "Members can read AI suggestions" SELECT policy (an inbox_items
-- membership join) already gates reads, and covers workspace-scoped queries.

COMMIT;
